# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ndL_VQdQb5aAy82c8ZUiQGfmAQhdDAxc
"""

# Uninstall potentially conflicting packages to ensure a clean slate
!pip uninstall -y sentence-transformers transformers torchvision torch Pillow gradio

# Install torch and torchvision first, as they are sensitive to Pillow versions
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# Install transformers and sentence-transformers next
!pip install transformers sentence-transformers

# Install other general dependencies, including pdfplumber.
# pdfplumber might try to install its own Pillow version, but
# torchvision and transformers would have already established a baseline.
!pip install pdfplumber python-docx PyPDF2 nltk scikit-learn

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

import pdfplumber
import docx
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from google.colab import files

uploaded = files.upload()

def extract_text(file_name):
    text = ""

    if file_name.endswith(".pdf"):
        with pdfplumber.open(file_name) as pdf:
            for page in pdf.pages:
                text += page.extract_text() or ""

    elif file_name.endswith(".docx"):
        doc = docx.Document(file_name)
        for para in doc.paragraphs:
            text += para.text + "\n"

    elif file_name.endswith(".txt"):
        with open(file_name, "r", encoding="utf-8") as f:
            text = f.read()

    return text

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)

    words = nltk.word_tokenize(text)
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]

    return " ".join(words)

SKILLS = [
    "python", "java", "c++", "machine learning", "deep learning",
    "nlp", "sql", "pandas", "numpy", "tensorflow", "keras",
    "django", "flask", "html", "css", "javascript"
]

def extract_skills(text):
    text = text.lower()
    found = []

    for skill in SKILLS:
        if skill in text:
            found.append(skill)

    return list(set(found))

model = SentenceTransformer('all-MiniLM-L6-v2')

def get_similarity(resume, job_desc):
    embeddings = model.encode([resume, job_desc])
    score = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
    return round(score * 100, 2)

job_desc = input("Enter Job Description: ")
job_desc = preprocess(job_desc)

results = []

for file_name in uploaded.keys():
    text = extract_text(file_name)
    clean_text = preprocess(text)

    score = get_similarity(clean_text, job_desc)
    skills = extract_skills(text)

    results.append({
        "name": file_name,
        "score": score,
        "skills": skills
    })

results = sorted(results, key=lambda x: x["score"], reverse=True)

for r in results:
    print(f"{r['name']} → {r['score']}% match")
    print(f"Skills: {r['skills']}")
    print("-" * 40)

import pandas as pd

df = pd.DataFrame(results)
df.to_csv("results.csv", index=False)

from google.colab import files
files.download("results.csv")